### PR TITLE
Switch license to BSD 3 Clause

### PR DESCRIPTION
**Pull request by manicki**
Per WMDE software licensing guidelines

### CODE REVIEW

**Comment by manicki** [comment]
@tarrow @toban As authors of the code in the repository, please state, in comment - not just by clicking the "approve" button, that you agree to the change of the license. Thanks

**Comment by tarrow** [comment]
Let's use the BSD license

**Comment by mariushoch** [comment]
Fine with me :)

**Comment by toban** [comment]
I'm Happy!

**Pull request merged**
